name: vlm-reward
channels:
  - defaults
dependencies:
  - python=3.9
  # please manually install conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
  - absl-py
  - pyparsing
  - pip
  - pip:
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+https://github.com/facebookresearch/hydra@0.11_branch
    - matplotlib
    - scikit-image
    - tqdm
    - moviepy